services:
  web:
    container_name: kkphim_core
    restart: unless-stopped
    image: ghcr.io/anvu69/kkphim-core:latest
    environment:
      - VIRTUAL_PORT=80
      - VIRTUAL_PROTO=http
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    ports:
      - 80
    networks:
      - default
    volumes:
      - ./nginx-site.conf:/var/www/html/conf/nginx/nginx-site.conf
      - ./php.ini:/usr/local/etc/php/conf.d/php.ini
      # - ./www.conf:/usr/local/etc/php-fpm.d/www.conf
      # - ./supervisor-config/:/etc/supervisor/conf.d/:rw
      - ./data:/var/www/html:rw

networks:
  default:
    name: ${NETWORK:-nginx_proxy}
    external: true